/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Dict {
    /**
     * 编码
     */
    code?: string;

    /**
     * 封面
     */
    cover?: string;

    /**
     * 创建人
     */
    createBy?: string;

    /**
     * 创建时间
     */
    createTime?: Date;

    /**
     * 描述
     */
    description?: string;

    /**
     * 主键
     */
    id?: string;

    /**
     * 名称
     */
    name?: string;

    /**
     * 父级id
     */
    parentId?: string;

    /**
     * 排序
     */
    sort?: number;

    /**
     * 状态（是否禁用）
     */
    status?: string;

    themeTypeList?: Array<models.Dict>;

    /**
     * 类型
     */
    type?: string;

    /**
     * 更新人
     */
    updateBy?: string;

    /**
     * 更新时间
     */
    updateTime?: Date;

}
